### ISSUE TITLE
Go-Live Checklist

### ISSUE THREAD

**Issue by c-e-p** [c-e-p/ourchive#74]
- [x] Set up Trello or Airtable (decision TBD)
- [x] Set up Trello report form
- [x] Buy prod domain(s)
- [x] Migrate user documentation to prod
- [x] Set up dev documentation in prod
- [x] Install Ourchive in prod
- [x] Set up Mailgun for prod
- [x] Set up prod landing site/homepage with links
- [x] Set up Mailgun API key for mailing lists
- [x] Create forum https://github.com/discourse/discourse/blob/main/docs/INSTALL-cloud.md
- [x] Create legal notice
- [x] Create privacy policy (https://github.com/Automattic/legalmattic/blob/master/Privacy-Policy.md)
- [x] Create code of conduct
- [ ] Link to legal notice & privacy policy in technical docs
- [ ] Let admins push notifications to users
- [ ] Contact email
- [ ] Security email

**Comment by c-e-p** [comment]
Invite list links: 
- https://twitter.com/stopthatimp/status/1687572543291465728 
- https://federatedfandom.net/@imp/110833419596304234
